# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverApp', '0008_auto_20160627_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominfo',
            name='is_available',
        ),
        migrations.AddField(
            model_name='hotelavailability',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelavailability',
            name='roomName',
            field=models.CharField(blank=True, max_length=5120, null=True),
        ),
    ]
