# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-28 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OverApp', '0008_auto_20160628_1127'),
        ('OverApp', '0009_auto_20160627_1333'),
    ]

    operations = [
    ]
