# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OverApp', '0013_auto_20160708_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginfo',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='bookinginfo',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='bookinginfo',
            name='package',
        ),
        migrations.RemoveField(
            model_name='bookinginfo',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='bookinginfo',
            name='room',
        ),
        migrations.DeleteModel(
            name='BookingInfo',
        ),
    ]
