# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverApp', '0014_auto_20160711_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelinfo',
            name='airportTransfer',
            field=models.FloatField(default=0),
        ),
    ]
