# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OverApp', '0016_auto_20160818_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='traveller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OverApp.Traveller'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OverApp.RoomInfo'),
        ),
    ]
