# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OverAppHelper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcache',
            old_name='merchant',
            new_name='traveller',
        ),
    ]
