# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverAppHelper', '0002_auto_20160711_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcache',
            name='checkin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookcache',
            name='checkout',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
