# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OverAppHelper', '0003_auto_20160711_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('booking_id', models.CharField(max_length=5120)),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverAppHelper.BookCache')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'BookingInfo',
            },
        ),
    ]
