# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverAppHelper', '0004_bookinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcache',
            name='checkin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bookcache',
            name='checkout',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
